/**
 * Frozen snapshot of a real LaunchLoop run.
 *
 * Generated by the live pipeline on 2026-08-30 against
 * github.com/hanamaraddi9620adi/swinglens: the analysis, both positioning
 * hypotheses, and both landing pages below are exactly what the model
 * produced, copied out of the database unedited.
 *
 * The /demo route replays this so the full loop can be shown even if live
 * generation is unavailable. Visitor counts and feedback that accompany it
 * come from the seeded events in demo-seed.ts and are labelled with their
 * true sample size — nothing here is a made-up number.
 */
export const DEMO_SNAPSHOT = {
  "analysis": {
    "product_name": "SwingLens",
    "summary": "SwingLens is a local-first stock analysis platform consisting of a Python FastAPI backend and a React frontend. It analyzes price charts to identify swing pivots, marks support/resistance, and builds entry/exit plans with an explainable confidence score, complemented by narrative blocks. It supports indicators, workflows, and chart-driven analytics with optional AI narration and a persistence layer.",
    "problem": "Provides an integrated, chart-driven workflow for retail traders to analyze swing setups, plan trades, and track performance without relying on external cloud-only tools; includes local persistence to preserve setups and results.",
    "target_users": [
      "Individual traders and investors performing swing trading or technical analysis",
      "Users who want an offline/local-first stock analysis environment",
      "Developers or data scientists prototyping AI-assisted market narratives (with optional LLM adapters)"
    ],
    "features": [
      "Chart-based swing analysis: detects swing pivots, marks support/resistance zones, and draws trendlines on price charts",
      "Automated trade planning: computes entry, stop, and target levels with an explainable confidence score",
      "Narrated analysis: generates four-block narration explaining math-backed results, with fallback when AI is unavailable",
      "Indicator toolbox: 27 configurable indicators organized by category (Trend, Momentum, Volatility, Volume, Levels)",
      "Setup persistence: saves and reuses setups, enabling self-grading across sessions",
      "Local-first architecture: data persisted locally (SQLite) via a data volume in Docker",
      "Frontend charting: interactive charts using lightweight-charts in a React app",
      "Extensible API: backend exposes routes for analysis, indicators, markets, stocks, news, portfolio, etc.",
      "AI/LLM integration: includes adapters for llm/cloud and Ollama (local) for narration",
      "Sample data and demos: provided sample CSV data and test suite to validate the engine",
      "Dockerized deployment: multi-stage Dockerfile and docker-compose setup for deployment",
      "Extensible architecture: modular backend with services for analysis_engine, indicators, narration, and more"
    ],
    "technical_capabilities": [
      "Backend: Python 3.12 FastAPI app with routing for authentication, analysis, indicators, markets, stocks, news, and portfolio",
      "Database: SQLite database stored at /data with a docker volume to preserve data across restarts",
      "Engine: Analytic engine (analysis_engine.py) performing chart analysis and setup scoring",
      "Narration: Narration service (narration.py) with LlM adapters (cloud, ollama) for deterministic or AI-generated narration",
      "Indicators: Catalog and configuration for multiple indicators via indicators.py and related services",
      "Trading data: Market data service (market_data.py) and markets/stocks routes for data retrieval",
      "Frontend: React-based UI with components for chat, charts, indicator management, and setup cards",
      "Testing: Backend tests (pytest) validating engine functionality",
      "Deployment: Docker-based build with frontend assets copied into the backend image",
      "Extensibility: Pluggable adapters for LLM and potential cloud providers"
    ],
    "differentiators": [
      "Local-first design ensuring data persistence and offline analysis capabilities",
      "Explainable trading plan: combines chart analysis results with a deterministic, math-based narration when AI is unavailable",
      "Integrated narrative blocks alongside quantitative results to aid decision-making",
      "Phase-driven feature set including a rich indicators toolbox and customizable setups",
      "Open architecture with a clear separation of concerns between analysis, indicators, narration, and data layers"
    ],
    "evidence": [
      "README describes SwingLens as a local-first stock analysis platform with Analyst Engine for pivots, zones, trendlines, breakout marking, entry/stop/target plan, and four-block narration",
      "Backend structure includes modules: services/analysis_engine.py, services/indicators.py, services/narration.py, and llm adapters (cloud_adapter.py, ollama_adapter.py)",
      "Frontend contains components for AIChat, IndicatorDialog, IndicatorChips, CandleChart, and multiple pages (Workspace, Portfolio, Explore), indicating chart-centric UI and indicator management",
      "Dockerfile and docker-compose.yml show a multi-stage build with a data volume at /data and an environment setup for running uvicorn backend",
      "Sample data in sample_data directory and tests in backend/tests/test_engine.py demonstrate engine validation",
      "API routes in backend/app/routers include analysis.py, indicators.py, news.py, markets.py, stocks.py, portfolio.py, scan.py, tracking.py, auth_routes.py, indicating a feature-rich backend API",
      "Frontend index.html and various React components reference charting, alerts, symbol news, and a setup card, consistent with a stock analysis and trading planning tool"
    ],
    "confidence": 0.72
  },
  "variants": [
    {
      "name": "a",
      "positioning": {
        "id": "a",
        "label": "Positioning A",
        "type": "outcome-pain",
        "target_audience": "Individual retail traders and investors performing swing trading or technical analysis who want offline, persistent analysis and clear trade planning",
        "primary_pain": "Dependency on cloud-only tools, fragmented workflows, and opaque trade plans that are hard to reproduce across sessions",
        "headline": "Trade smarter, offline and with confidence: swing analysis that sticks with you between sessions",
        "subheadline": "Local-first chart analytics + explainable entry/exit plans—without sacrificing speed or insight",
        "main_promise": "Deliver an end-to-end, offline swing-trading workflow that produces repeatable, explainable plans and keeps all setups and results locally",
        "benefits": [
          "Offline-first, persistent analysis that preserves progress across sessions",
          "Explainable, math-backed trade plans with confidence scores",
          "Integrated narrative blocks to quickly understand why a setup works"
        ],
        "cta": "Start your offline trading workflow",
        "proof_angle": "Compared against typical cloud-based tools, SwingLens offers local persistence, reproducible results, and a transparent confidence scoring narrative; includes sample data and test suite",
        "why_this_framing": "Addresses a core pain point for self-directed traders who need reliability, privacy, and reproducibility without cloud dependence",
        "color_scheme": {
          "primary": "#1E3A8A",
          "secondary": "#F59E0B",
          "accent": "#10B981"
        }
      },
      "landing": {
        "hero": {
          "headline": "Trade smarter, offline and with confidence: swing analysis that sticks with you between sessions",
          "subheadline": "Local-first chart analytics + explainable entry/exit plans—without sacrificing speed or insight",
          "cta": "Start your offline trading workflow",
          "ctaSubtext": "No data leaves your device. Reproducible results. Transparent confidence scores."
        },
        "problem": {
          "title": "The friction of cloud-only tools breaks your workflow",
          "description": "Retail traders lose momentum when setups drift between sessions, data migrates to the cloud, and plans become opaque. You need persistent, explainable analysis that stays with you offline.",
          "painPoints": [
            "Dependency on cloud services that slow you down or risk data access",
            "Fragmented workflows with no reliable way to reproduce setups across sessions",
            "Opaque trade plans and confidence metrics that are hard to audit or explain"
          ]
        },
        "benefits": {
          "title": "What you gain with SwingLens",
          "items": [
            {
              "title": "Offline-first persistence",
              "description": "All analysis, setups, and results live locally, preserving progress across sessions."
            },
            {
              "title": "Explainable, math-backed plans",
              "description": "Entry, stop, target, and a confidence score you can trust—transparent and reproducible."
            },
            {
              "title": "Narrative clarity in an instant",
              "description": " Four-block narration explains why a setup works, with fallback when AI is unavailable."
            }
          ]
        },
        "howItWorks": {
          "title": "End-to-end, offline swing workflow in four parts",
          "steps": [
            {
              "step": 1,
              "title": "Chart-based analysis",
              "description": "Automatically detect swing pivots, mark support/resistance, and draw trendlines on local charts."
            },
            {
              "step": 2,
              "title": "Automated planning",
              "description": "Compute entry, stop, and target levels with an explainable confidence score."
            },
            {
              "step": 3,
              "title": "Narrated insight",
              "description": "Generated four-block narration that explains math-backed results; available offline."
            },
            {
              "step": 4,
              "title": "Persistent setups",
              "description": "Save and reuse setups across sessions to self-grade and reproduce results."
            }
          ]
        },
        "features": {
          "title": "What’s inside SwingLens",
          "items": [
            {
              "title": "Chart-based swing analysis",
              "description": "Detect pivots, mark zones, and draw trendlines directly on price charts.",
              "icon": "chart"
            },
            {
              "title": "Automated trade planning",
              "description": "Compute entry/stop/target with a transparent confidence score.",
              "icon": "target"
            },
            {
              "title": "Narrated analysis",
              "description": "Four-block narration that explains results; fallback if AI is offline.",
              "icon": "book"
            },
            {
              "title": "Indicator toolbox",
              "description": "27 configurable indicators across Trend, Momentum, Volatility, Volume, and Levels.",
              "icon": "indicator"
            },
            {
              "title": "Setup persistence",
              "description": "Save, reuse, and self-grade setups across sessions.",
              "icon": "save"
            },
            {
              "title": "Local-first architecture",
              "description": "SQLite data persisted locally via a Docker data volume.",
              "icon": "database"
            },
            {
              "title": "Extensible API",
              "description": "Backend routes for analysis, indicators, markets, stocks, news, and portfolios.",
              "icon": "api"
            },
            {
              "title": "AI/LLM integration",
              "description": "Adapters for cloud LLMs and Ollama (local) for narration and insight.",
              "icon": "ai"
            }
          ]
        },
        "cta": {
          "headline": "Take back control of your swing trading",
          "subheadline": "Start your offline trading workflow today and keep every insight on your terms.",
          "button": "Start your offline trading workflow"
        }
      }
    },
    {
      "name": "b",
      "positioning": {
        "id": "b",
        "label": "Positioning B",
        "type": "capability-transformation",
        "target_audience": "Developers, data scientists, and AI enthusiasts prototyping AI-assisted market narratives and extensible analytics",
        "primary_pain": "Fragmented tooling and opaque AI narration that’s hard to integrate or customize in a scalable way",
        "headline": "Transform your market analysis: a modular, local-first platform that you can extend and automate",
        "subheadline": "Open architecture with extensible API, local persistence, and pluggable AI narration adapters (LLM/cloud or Ollama)",
        "main_promise": "Empower builders to prototype, customize, and extend swing analysis, indicators, and AI-driven narratives in a secure, offline-ready environment",
        "benefits": [
          "Modular backend with clear service boundaries (analysis, indicators, narration, data)",
          "Local persistence via SQLite and Dockerized deployment for offline-first workflows",
          "Extensible API and AI adapters for custom narrations and models"
        ],
        "cta": "Build your analytics & narratives locally",
        "proof_angle": "Open architecture, Dockerized deployment, and adapters for multiple AI backends; includes sample data, test suite, and documented APIs",
        "why_this_framing": "Appeals to builders who want control, customization, and reliable offline operation, differentiating from consumer-only or cloud-centric tools",
        "color_scheme": {
          "primary": "#374151",
          "secondary": "#34D399",
          "accent": "#6366F1"
        }
      },
      "landing": {
        "hero": {
          "headline": "Transform your market analysis: a modular, local-first platform that you can extend and automate",
          "subheadline": "Open architecture with extensible API, local persistence, and pluggable AI narration adapters (LLM/cloud or Ollama)",
          "cta": "Build your analytics & narratives locally",
          "ctaSubtext": "Prototype, customize, and extend swing analysis in a secure offline-ready environment"
        },
        "problem": {
          "title": "Fragmented tooling and opaque AI narration",
          "description": "Disparate tools and closed narration engines slow innovation, lock you into one vendor, and force compromising tradeoffs between security, offline capability, and extensibility.",
          "painPoints": [
            "Hard to integrate diverse analytics, indicators, and AI narratives into a single workflow",
            "Opaque, non-customizable narration that hinders explainability and auditability",
            "Weak offline-first support and local persistence for sensitive data"
          ]
        },
        "benefits": {
          "title": "Why SwingLens changes the game",
          "items": [
            {
              "title": "Modular backend with clear boundaries",
              "description": "Separate services for analysis, indicators, narration, and data to speed iteration and improve governance."
            },
            {
              "title": "Local persistence and offline-first",
              "description": "SQLite + Dockerized deployment ensures data integrity and offline workflows without cloud dependency."
            },
            {
              "title": "Extensible API and AI adapters",
              "description": "Plug in custom narrations, models, and AI backends to match your data strategy and compliance needs."
            }
          ]
        },
        "howItWorks": {
          "title": "How SwingLens empowers your team",
          "steps": [
            {
              "step": 1,
              "title": "Prototype with modular services",
              "description": "Analyze pivots, draw trendlines, and compute indicators with clearly defined service boundaries."
            },
            {
              "step": 2,
              "title": "Narrate with flexible AI backends",
              "description": "Choose cloud LLMs or local Ollama adapters for explainable, deterministic narration."
            },
            {
              "step": 3,
              "title": "Persist and iterate locally",
              "description": "Store setups, data, and results in a Docker-contained SQLite volume for repeatable experiments."
            }
          ]
        },
        "features": {
          "title": "Core capabilities",
          "items": [
            {
              "title": "Chart-based swing analysis",
              "description": "Detect swing pivots, mark support/resistance zones, and draw trendlines on price charts.",
              "icon": "chart-swing"
            },
            {
              "title": "Automated trade planning",
              "description": "Compute entry, stop, and target levels with a transparent confidence score.",
              "icon": "target"
            },
            {
              "title": "Narrated analysis",
              "description": "Four-block narration explaining math-backed results; fallback when AI is unavailable.",
              "icon": "speech-bubble"
            },
            {
              "title": "Indicator toolbox",
              "description": "27 configurable indicators across Trend, Momentum, Volatility, Volume, and Levels.",
              "icon": "indicator"
            },
            {
              "title": "Setup persistence",
              "description": "Save and reuse setups; enabling self-grading across sessions.",
              "icon": "database"
            },
            {
              "title": "Local-first architecture",
              "description": "Data persisted locally via SQLite in a Docker volume for offline workflows.",
              "icon": "database-lock"
            },
            {
              "title": "Extensible API",
              "description": "Backend routes for analysis, indicators, markets, stocks, news, portfolio, and more.",
              "icon": "api"
            },
            {
              "title": "AI/LLM integration",
              "description": "Adapters for cloud LLMs and Ollama (local) for deterministic or AI-generated narration.",
              "icon": "robot"
            },
            {
              "title": "Sample data and tests",
              "description": "Provided CSV samples and a test suite to validate the engine and workflows.",
              "icon": "sparkles"
            },
            {
              "title": "Dockerized deployment",
              "description": "Multi-stage Dockerfile and docker-compose for consistent local-to-prod setups.",
              "icon": "docker"
            },
            {
              "title": "Extensible architecture",
              "description": "Modular backend with services for analysis_engine, indicators, narration, and more.",
              "icon": "cubes"
            }
          ]
        },
        "cta": {
          "headline": "Get started with SwingLens today",
          "subheadline": "Open architecture, Dockerized deployment, and adapters for multiple AI backends. Includes sample data, test suite, and documented APIs.",
          "button": "Build your analytics & narratives locally"
        }
      }
    }
  ]
} as const;

/**
 * The V3 proposal the model produced from the seeded results above.
 * Baked in so /demo can show the closing step of the loop without making a
 * live AI call, which is the whole point of having a fallback route.
 */
export const DEMO_LEARNING = {
  "winner": "a",
  "confidence": "Early directional signal in favor of Variant A, but based on very small samples (n=11 for A, n=10 for B). No statistical significance can be claimed at this stage.",
  "observations": [
    "Variant A shows higher conversion rate (36.4%) vs Variant B (20.0%), with 4/11 vs 2/10 CTA clicks respectively.",
    "Visitor feedback for Variant A includes confusion around whether the product is a broker and what 'explainable confidence score' means; there is tone of curiosity and skepticism about features.",
    "Variant B feedback indicates emphasis on architecture and capability, but visitors want concrete outcomes and day-one value; some comments suggest interest in self-hosting and API angles.",
    "Overall, A’s positioning around 'Outcome/Offline capability' appears more aligned with practical trading use, given the feedback about offline trading selling point.",
    "Small sample sizes limit the ability to generalize; qualitative feedback is highly informative for messaging clarity."
  ],
  "visitor_confusion": [
    "Is SwingLens a broker or trading platform? (Variant A feedback)",
    "What does 'explainable confidence score' actually mean? Is it a backtest? (Variant A feedback)",
    "What exactly do I get on day one with this product? (Variant B feedback)",
    "The term 'swing' was misinterpreted initially; terminology needs clarity (Variant A feedback)",
    "Some visitors interpret the content as infrastructure-focused rather than a trading tool (Variant B feedback)"
  ],
  "strongest_message": "Variant A’s emphasis on offline capability and tangible swing trading support (plus a notion of explainable scoring) appears to resonate more with visitors, even if messaging requires clarification.",
  "weakest_message": "For both variants, unclear or ambiguous terminology (broker, explainable confidence score, day-one value) diluted the impact. Variant B’s architectural framing didn’t clearly translate to trading outcomes for users.",
  "recommended_changes": "1) Clarify core value on day one: present concrete, step-by-step outcomes (e.g., 'Identify swing pivots, generate entry/exit plan, 1-click backtest-ready signals'). 2) Define terms plainly: explain what 'explainable confidence score' means with a simple example; avoid broker/trading platform ambiguity. 3) Reduce architectural jargon and emphasize practical use-cases over structure. 4) Highlight offline/low-bandwidth benefits with concrete scenarios (e.g., when wifi is unreliable). 5) Consider a combined positioning variant that foregrounds outcome/results and offline reliability, with a tiny snippet showing a sample plan and a simple score interpretation. 6) Add onboarding copy or a hero section showing what you get today (day one) vs. roadmap features to reduce perceived risk.",
  "next_hypothesis": "A revised hybrid positioning that foregrounds concrete trading outcomes and offline reliability (e.g., 'SwingLens gives you actionable swing plans that work offline with a simple explainable score'), along with a clarified definition of the score and day-one deliverables, will improve clarity and conversions. Test a new variant that (a) defines day-one value, (b) explains the score with a concrete example, and (c) minimizes architectural jargon. If feasible, run a small split test pairing this messaging with a short, visual demo showing a real-world swing setup and outcome feedback."
} as const;

/**
 * The V3 proposal generated from the seeded run above.
 *
 * Frozen from a real call against this experiment, so /demo can show the
 * step the whole product turns on without spending a model call — or
 * needing the network — on every visit. The change list is what the
 * product computed by comparing the stored strings, not a description the
 * model wrote about its own edits.
 */
export const DEMO_V3 = {
  "basedOnVariant": "a",
  "sampleFeedbackCount": 8,
  "summary": "This revision emphasizes concrete day-one outcomes and a clear explainable score, while retaining offline, local-first advantages and avoiding architectural jargon to improve clarity and perceived value.",
  "changes": [
    {
      "field": "headline",
      "label": "Headline",
      "before": "Trade smarter, offline and with confidence: swing analysis that sticks with you between sessions",
      "after": "Trade smarter offline: actionable swing plans you can trust across sessions",
      "reason": "Changed to foreground offline capability and tangible swing outcomes based on visitors' emphasis on offline reliability and real trading support (early feedback favored offline and explainable scoring but noted need for concrete day-one outcomes)."
    },
    {
      "field": "subheadline",
      "label": "Subheadline",
      "before": "Local-first chart analytics + explainable entry/exit plans—without sacrificing speed or insight",
      "after": "Local-first chart analytics + concrete day-one outcomes and an explainable score—without sacrificing speed",
      "reason": "Incorporates day-one outcomes and a simple explainable score to address confusion about what is delivered immediately, per visitor notes about day-one value and score clarity."
    },
    {
      "field": "main_promise",
      "label": "Main promise",
      "before": "Deliver an end-to-end, offline swing-trading workflow that produces repeatable, explainable plans and keeps all setups and results locally",
      "after": "Deliver an end-to-end, offline swing-trading workflow that yields concrete day-one results: identify swing pivots, generate entry/exit plans, and present a simple explainable score—all kept locally",
      "reason": "Explicitly states day-one deliverables (pivots, plans, explainable score) to fix feedback about unclear day-one value and outcomes."
    },
    {
      "field": "primary_pain",
      "label": "Primary pain",
      "before": "Dependency on cloud-only tools, fragmented workflows, and opaque trade plans that are hard to reproduce across sessions",
      "after": "Dependency on cloud-only tools, fragmented workflows, and opaque trade plans that are hard to reproduce across sessions; confusion about what you get on day one and what the explainable score means",
      "reason": "Adds clarity about day-one value and explains the score to counter confusion and ambiguity from feedback; retains offline/reproducible themes."
    }
  ]
} as const;
